version: "3.9"

networks:
  isolation-network:
    driver: bridge

services:

  analytics:
    build: ./analytics
    container_name: analytics
    ports:
      - "8082:8080"
    environment:
      spring.datasource.url: "jdbc:mysql://db/docker"
      spring.datasource.username: "root"
      spring.datasource.password: "1234"
    networks:
      - isolation-network


  authentication:
    build: ./AuthenticationService
    container_name: authentication
    ports:
      - "8081:8080"
    environment:
      spring.datasource.url: "jdbc:mysql://db/docker"
      spring.datasource.username: "root"
      spring.datasource.password: "1234"
    networks:
      - isolation-network


  showresult:
    build: ./showResult
    container_name: showresult
    ports:
      - "8083:8080"
    environment:
      spring.datasource.url: "jdbc:mysql://db/docker"
      spring.datasource.username: "root"
      spring.datasource.password: "1234"
    networks:
      - isolation-network

  dataentry:
    build: ./webApp
    container_name: dataentry
    ports:
      - "8080:8080"
    environment:
      spring.datasource.url: "jdbc:mysql://db/docker"
      spring.datasource.username: "root"
      spring.datasource.password: "1234"
    networks:
      - isolation-network


  db:
    image: mysql:8
    container_name: mysql
    restart: always
    command: --init-file /data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: docker
    volumes:
      - database:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    networks:
      - isolation-network


volumes:
  database:
    external: false
